DROP TABLE follower IF EXISTS;
DROP TABLE wpis IF EXISTS;
DROP TABLE uzytkownik IF EXISTS;

CREATE TABLE uzytkownik (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login        VARCHAR(50) NOT NULL UNIQUE,
    email        VARCHAR(100) NOT NULL UNIQUE,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE follower (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    follows_user_id INTEGER NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_follower_user
        FOREIGN KEY (user_id) REFERENCES uzytkownik(id),
    CONSTRAINT fk_follower_follows
        FOREIGN KEY (follows_user_id) REFERENCES uzytkownik(id),

    CONSTRAINT chk_not_self_follow CHECK (user_id <> follows_user_id),
    CONSTRAINT uq_follow_pair UNIQUE (user_id, follows_user_id)
);

CREATE TABLE wpis (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL,
    tresc        VARCHAR(500) NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_wpis_user
        FOREIGN KEY (user_id) REFERENCES uzytkownik(id)
);